name: vumi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_html: 2.2.1
  photo_view: 0.14.0
  get_storage: 2.0.3
  translator: 0.1.7
  intl: any
  qr_code_scanner: 1.0.1
  permission_handler: 10.2.0
  flutter_inappwebview: 5.7.2+3
  flutter_easyloading: 3.0.5
  flutter_screenutil: 5.6.1
  google_fonts: 4.0.3
  pdf: 3.6.0
  path: any
  path_provider: 2.0.13
  open_filex: 4.3.2
  bangla_utilities: 1.0.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.11.0
  flutter_app_name: 0.1.1
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/locates/bn_BD.json
    - assets/locates/en_US.json
    - assets/fonts/Roboto/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: kalpurush
      fonts: 
        - asset: assets/fonts/kalpurush/kalpurush.ttf
  generate: true
  uses-material-design: true

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/icon.png
  windows: 
    image_path: assets/images/icon.png
    generate: true
    icon_size: 48
  ios: true

flutter_app_name: 
  name: ভূমিসেবা

